### ISSUE TITLE
h5项目需要添加默认样式

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#7]
```css
* {
  padding: 0;
  margin: 0;
  box-sizing: border-box;
}
html,
body,
#root {
  width: 100%;
  height: 100%;
}
body {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  -webkit-overflow-scrolling: touch;
}
input {
  border: none;
  outline: none;
}
#root {
  position: relative;
  overflow: scroll;
}

textarea:disabled,
input:disabled {
  background-color: transparent;
}
```
